apiVersion: v1
kind: Service
metadata:
  name: goat-tweet-analyzer
spec:
  selector:
    app: goat-tweet-analyzer
    tier: backend
  ports:
  - protocol: "TCP"
    port: 4100
    targetPort: 4100
  type: LoadBalancer

